### ISSUE TITLE
-Xmx doesn't apply

### ISSUE THREAD

**Issue by voyagerlife** [scorta/GuessPrivateKey#6]
Without -Xmx the program only imports 6 addresses. And with -Xmx flag I get the following error.

C:\Windows\System32\GuessPrivateKey>java -jar GuessPrivateKey.jar 3 bit.txt -Xmx1024m random
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant GuessKeyThread.CHOICE.-Xmx1024m
        at java.lang.Enum.valueOf(Unknown Source)
        at GuessKeyThread$CHOICE.valueOf(GuessPrivateKey.java:48)
        at GuessPrivateKey.main(GuessPrivateKey.java:21)

**Comment by scorta** [comment]
Hm, I believe without -Xmx, the program can still import a lot of addresses. I think your problem is because of putting "-Xmx1024m" at the wrong place: -Xmx is passed to java, not my program, so your command should be:
`java -jar -Xmx1024m GuessPrivateKey.jar 3 bit.txt random`
Please give it a try. Cheer!
PS. I believe `random` is a bad choice. Should have used `up` or `down` (Unless you are the luckiest person in this universe :p) And also, read my comment in other thread about this program: https://github.com/scorta/GuessPrivateKey/issues/5#issuecomment-471395577
